/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Tue Mar  5 11:48:52 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_VEGAPVW 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_VEGAPVW
machine_is_msm8960_vegapvw() function
*/

#define PT10  0x01
#define PT11  0x02
#define WS10  0x04
#define WS11  0x08
#define WS20  0x10
#define ES10  0x20
#define ES20  0x40
#define TP10  0x80

#define BOARD_VER   TP10
#endif /*BOARD_REV_H*/
